import Foundation

/// Generates user-friendly default scan titles like "Scan 1", "Scan 2", ...
/// Persists a counter in UserDefaults so numbering continues across app restarts.
enum ScanNamingService {
    private static let counterKey = "monkscan.scan.counter"
    
    static func nextTitle(userDefaults: UserDefaults = .standard) -> String {
        let current = userDefaults.integer(forKey: counterKey) // defaults to 0
        let next = current + 1
        userDefaults.set(next, forKey: counterKey)
        return "Scan \(next)"
    }
    
    static func isAutoGeneratedTitle(_ title: String) -> Bool {
        guard title.hasPrefix("Scan ") else { return false }
        let suffix = title.dropFirst("Scan ".count)
        return Int(suffix) != nil
    }
}


